---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: bitnami/spark:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPARK_MODE
              value: worker
            - name: SPARK_MASTER_URL
              value: spark://spark-master-service:7077
            - name: SPARK_WORKER_MEMORY
              value: 2G
            - name: SPARK_WORKER_CORES
              value: '2'
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: 'no'
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: 'no'
            - name: SPARK_SSL_ENABLED
              value: 'no'
            - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
              value: 'no'
